config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'quotes#index'

  resources :quotes do
    resources :items, except: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  TVA = 1.20

  belongs_to :quote

  validates :name, presence: true
  validates :quantity,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than: 0
            }
  validates :pre_tax_unit_price_cents,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0
            }

  monetize :pre_tax_unit_price_cents,
            allow_nil: false,
            numericality: { greater_than_or_equal_to: 0 }
  monetize :pre_tax_total_price_cents,
            allow_nil: false,
            numericality: { greater_than_or_equal_to: 0 }
  monetize :total_price_cents,
            allow_nil: false,
            numericality: { greater_than_or_equal_to: 0 }

  scope :ordered, -> { order(id: :asc) }

  before_validation :calculate_totals

  private

  def calculate_totals
    calculate_pre_tax_total
    calculate_total
  end

  def calculate_pre_tax_total
    self.pre_tax_total_price_cents = pre_tax_unit_price_cents * quantity
  end

  def calculate_total
    self.total_price_cents = (pre_tax_total_price_cents * TVA).round
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true

  monetize :pre_tax_total_price_cents
  monetize :total_price_cents
  monetize :total_tax_cents

  def pre_tax_total_price_cents
    items.sum(&:pre_tax_total_price_cents)
  end

  def total_price_cents
    items.sum(&:total_price_cents)
  end

  def total_tax_cents
    total_price_cents - pre_tax_total_price_cents
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_quote
  before_action :set_item, only: [:show, :edit, :update, :destroy]


  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = @quote.items.build(item_params)

    if @item.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @quote }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @item.update(item_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @quote }
      end
    else
      render :edit
    end
  end


  def destroy
    @item.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @quote }
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :quantity, :pre_tax_unit_price)
  end

  def set_quote
    @quote = Quote.find(params[:quote_id])
  end

  def set_item
    @item = @quote.items.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]
  # skip_after_action :verify_policy_scoped
  # skip_after_action :verify_authorized

  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, except: [:index, :new, :create]

  def index
    @quotes = Quote.all.order(created_at: :desc)
    @quote = Quote.new
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.prepend(:quotes, partial: "quotes/quote", locals: { quote: @quote } )}
        format.html { redirect_to quotes_path }
      end
    else
      render :new
    end

  end

  def edit
  end

  def update
      if @quote.update(quote_params)
        redirect_to quotes_path, notice: "Quote was successfully updated."
      else
        render :edit
      end
  end


  def destroy
    @quote.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@quote) }
      format.html { redirect_to quotes_path }
    end
  end

  private

  def quote_params
    params.require(:quote).permit(:name)
  end

  def set_quote
    @quote = Quote.eager_load(:items).merge(Item.ordered).find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= simple_form_for [ quote, item ],
  html: { id: dom_id(item) },
  data: { controller: "form", action: "turbo:submit-end->form#reset" } do |f| %>

  <div>
    <%= f.input :name, required: true, label: false, placeholder: "* Name", input_html: {class: "rounded min-w-full mt-5"} %>
    <%= f.input :description, required: false, label: false, placeholder: "Description", input_html: {class: "rounded min-w-full mt-5"} %>
    <%= f.input :quantity, required: true, label: false, placeholder: "* Quantity", input_html: {class: "rounded min-w-full mt-5"} %>
    <%= f.input :pre_tax_unit_price, required: true, label: false, placeholder: "* Pre tax unit price", input_html: {class: "rounded min-w-full mt-5"} %>
    <div class="flex justify-between mt-2">
      <%= f.submit "Save", class: "cursor-pointer rounded bg-green text-white mt-5 p-2 ml-2" %>
      <%= link_to "Cancel", quote_path(quote), class: "rounded bg-gray mt-5 p-2" %>
    </div>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= turbo_frame_tag dom_id(item) do %>
  <div class="flex grid grid-cols-7 grid-rows-1  mt-2 p-2 rounded">
    <div class="col-start-1 col-end-auto">
      <h2 class="bold text-lg"><%= item.name %></h2>
      <p class="text-sm"><%= item.description %></p>
    </div>
    <div class="col-start-2 col-end-auto text-right pr-5"><%= item.quantity %></div>
    <div class="col-start-3 col-end-auto text-right  pr-5"><%= humanized_money_with_symbol item.pre_tax_unit_price %></div>
    <div class="col-start-4 col-end-auto text-right  pr-5"><%= humanized_money_with_symbol item.pre_tax_total_price %></div>
    <div class="col-start-5 col-end-auto text-right"><%= humanized_money_with_symbol item.total_price %></div>
    <div class="col-start-6 col-end-auto text-center">
      <%= link_to "edit", edit_quote_item_path(quote, item), class: "mx-2 pt-1 text-sm text-green" %>
    </div>
    <div class="col-start-7 col-end-auto">
      <%= button_to "remove", quote_item_path(quote, item), method: :delete, class: "mx-2 text-sm text-red" %>
    </div>
  </div>
<% end %>

app/views/items/_new_item_link.html.erb
<%= turbo_frame_tag "item_form", class: "m-5" do %>
  <%= link_to "Add an item", new_quote_item_path(quote), class: "rounded p-2 bg-green text-white" %>
<% end %>

app/views/items/create.turbo_stream.erb
<%= turbo_stream.append "items"  do %>
  <%= render @item, quote: @quote %>
<% end %>

<%= turbo_stream.replace "item_form"  do %>
  <%= render "items/new_item_link", quote: @quote %>
<% end %>

<%= turbo_stream.replace "total_prices"  do %>
  <%= render "quotes/total_prices", quote: @quote %>
<% end %>

app/views/items/destroy.turbo_stream.erb
<%= turbo_stream.remove @item %>

<%= turbo_stream.replace "total_prices"  do %>
  <%= render "quotes/total_prices", quote: @quote %>
<% end %>

app/views/items/edit.html.erb
<%= turbo_frame_tag @item do %>
  <div class="border rounded p-2 my-4">
    <%= render 'items/form', quote: @quote, item: @item %>
  </div>
<% end %>

app/views/items/new.html.erb
<%= turbo_frame_tag "item_form", class: "mt-5" do %>
  <%= render "items/form", item: @item, quote: @quote %>
<% end %>

app/views/items/show.html.erb
<%= render @item, quote: @quote %>

app/views/items/update.turbo_stream.erb
<%= turbo_stream.replace @item do %>
  <%= render @item, quote: @quote %>
<% end %>

<%= turbo_stream.replace "total_prices"  do %>
  <%= render "quotes/total_prices", quote: @quote %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container min-h-screen mx-auto mt-7 px-5 flex justify-center bg-gray pt-20">
      <div class="w-3/4 flex flex-col">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/quotes/_form.html.erb
<%= simple_form_for quote,
  html: { id: dom_id(quote) },
  data: { controller: "form", action: "turbo:submit-end->form#reset" },
  class: "w-full" do |f| %>

  <div class="flex w-full">
      <%= f.input :name, required: true, label: false, placeholder: "* Quote name", input_html: {class: "flex-[1-1-0] w-full rounded min-w-full"} %>

      <%= f.submit "Save", class: "w-30 cursor-pointer rounded bg-green text-white p-2 ml-2" %>

    <% if quote.persisted? %>
      <%= link_to "Cancel", quotes_path, class: "w-30 rounded bg-gray p-2 ml-2" %>
    <% end %>
  </div>


<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag dom_id(quote) , class: "mt-5 flex justify-between w-full border rounded p-2 bg-blue" do %>
  <%= link_to quote.name, quote_path(quote), "data-turbo-frame": "_top", class: "cursor-pointer" %>
  <div class="flex">
    <%= link_to "edit", edit_quote_path(quote), class: "mx-2 pt-1 text-sm text-green" %>
    <%= button_to "remove", quote_path(quote), method: :delete, class: "mx-2 text-sm text-red" %>
  </div>
<% end %>

app/views/quotes/_total_prices.html.erb
<div id="total_prices" class="font-bold w-1/3 my-7 border rounded p-5 bg-white">
  <div class="flex justify-between">
    <p>Total excl tax :</p>
    <p><%= humanized_money_with_symbol quote.pre_tax_total_price %></p>
  </div>
  <div class="flex justify-between mt-5">
    <p>Total VAT :</p>
    <p><%= humanized_money_with_symbol quote.total_tax %></p>
  </div>
  <div class="flex justify-between mt-5">
    <p>Total incl tax :</p>
    <p><%= humanized_money_with_symbol quote.total_price %></p>
  </div>
</div>

app/views/quotes/edit.html.erb
<%= turbo_frame_tag dom_id(@quote), class: "mt-2" do %>
  <%= render "quotes/form", quote: @quote %>
<% end %>

app/views/quotes/index.html.erb
<h1 class="font-bold text-3xl text-center mb-7">Quotes</h1>

<%= turbo_frame_tag "quote_form", class: "mt-5" do %>
  <%= render "quotes/form", quote: @quote %>
<% end %>

<div id="quotes" class="flex flex-col mt-5">
  <%= render @quotes %>
</div>

app/views/quotes/new.html.erb
<%= turbo_frame_tag "quote_form", class: "mt-5", target: "_top" do %>
  <%= render "quotes/form", quote: @quote %>
<% end %>

app/views/quotes/show.html.erb
<div>
  <h1 class="text-2xl font-bold text-center my-5"><%= @quote.name %></h1>
  <div class="bg-white p-5 rounded">

    <div class="flex grid grid-cols-7 grid-rows-1 font-bold">
      <div class="col-start-1 col-end-auto text-left">Product and description</div>
      <div class="text-right col-start-2 col-end-auto pr-5">Quantity</div>
      <div class="text-right col-start-3 col-end-auto pr-5">Unit price</div>
      <div class="text-right col-start-4 col-end-auto pr-5">Total excl tax</div>
      <div class="text-right col-start-5 col-end-auto">Total incl tax</div>
    </div>
    <div id="items" class="mb-5">
      <%= render @quote.items, quote: @quote %>
    </div>

    <%= render "items/new_item_link", quote: @quote %>
  </div>

  <%= render "quotes/total_prices", quote: @quote %>

  <%= link_to "Back to quotes", quotes_path, class: "bg-green text-white rounded p-2" %>

</div>